### ISSUE TITLE
Cyclical Dependencies

### ISSUE THREAD

**Issue by adamrmcclain** [berfinsari/tracebeat#1]
I'm trying to build this project, but am seeing the following error:

import cycle not allowed
package github.com/berfinsari/tracebeat
        imports github.com/berfinsari/tracebeat/beater
        imports github.com/elastic/beats/libbeat/publisher
        imports github.com/elastic/beats/libbeat/outputs
        imports github.com/elastic/beats/libbeat/publisher

I'd guess that there are some issues with the new version of the elastic code base causing this? Any chance you could update your code base to work with the new elastic changes? Thanks

**Comment by berfinsari** [comment]
Currently, tracebeat is not compatible with the latest version of beats. I will fix this issue. Thanks for informing.

**Comment by berfinsari** [comment]
A fix is available on master. Will try to make a release soon.
